### ISSUE TITLE
    Error java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I

### ISSUE THREAD

**Issue by devrajeev** [aspnet/SignalR-samples#51] opened 2018-10-07 18:01 UTC
I am facing below error at hubConnection.on("ReceiveMessage",..):
    java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I

dependency 

> implementation 'com.microsoft.aspnet:signalr:0.1.0-preview1-35029'

here throwing that error
> hubConnection.on("ReceiveMessage", (message)-> {
> 
>             getActivity().runOnUiThread(new Runnable() {
>                 @Override
>                 public void run() {
>                     Log.d("MessageReceived",message);
>                     arrayAdapter.add(senderName + " : " +message);
>                     arrayAdapter.notifyDataSetChanged();
>                 }
>             });
>         }, String.class);

Find below error source

**10-07 23:24:39.425 18779-18779/com.cabieo.cabieoapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I>
10-07 23:24:39.425 18779-18779/com.cabieo.cabieoapp D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
10-07 23:24:39.600 18779-18779/com.cabieo.cabieoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cabieo.cabieoapp, PID: 18779
    java.lang.NoClassDefFoundError: com.microsoft.aspnet.signalr.-$$Lambda$CallbackMap$V5Uq2tEgd64-ZwWFXygwi8ZeV4I
        at com.microsoft.aspnet.signalr.CallbackMap.put(CallbackMap.java:15)
        at com.microsoft.aspnet.signalr.HubConnection.on(HubConnection.java:219)
        at com.cabieo.cabieoapp.Fragments.ChatHomeFragment.onCreateView(ChatHomeFragment.java:70)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
10-07 23:24:39.607 5240-5310/? I/octvm_klo: klo lock**

**Comment by mikaelm12** [comment] 2018-12-13 22:06
We haven't reproduced this product issue. It looks like this was in Preview 1 of the Java client release as well. It's likely that you wont see this issue in the newly released 1.0 version of the client. Going to close this but feel free to still comment with follow ups and we can re open as necessary.

**Closed by mikaelm12** 2018-12-13 22:06 UTC

**Comment by shudson302** [comment] 2019-07-15 16:16
I am still having this issue with version 1.0.0 of SignalR and java vesrion 12.0.1 of java.  I am using the SignalRChat sample from the AspNetCore.Docs sample found here:

https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/java-client/sample

Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/signalr/HubConnectionBuilder
        at Chat.main(Chat.java:16)
Caused by: java.lang.ClassNotFoundException: com.microsoft.signalr.HubConnectionBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

**Comment by bradygaster** [comment] 2019-07-18 17:36
cc @mikaelm12 - anything stand out to you here?

**Comment by shudson302** [comment] 2019-07-18 18:34
Im not sure how to verify that.

 mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for test-java-client:test:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -----------------------< test-java-client:test >------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\SummerHudson\source\repos\AspNetCore.Docs\aspnetcore\signalr\java-client\sample\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\SummerHudson\source\repos\AspNetCore.Docs\aspnetcore\signalr\java-client\sample\src\test\resources
[INFO]


[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.812 s
[INFO] Finished at: 2019-07-18T13:32:00-05:00
[INFO] ------------------------------------------------------------------------
PS C:\Users\SummerHudson\source\repos\AspNetCore.Docs\aspnetcore\signalr\java-client\sample>

__________________________________________________________________________________________________________________

Run
 java -cp target/test-1.0-SNAPSHOT.jar Chat
Enter the URL of the SignalR Chat you want to join
https://nidprintserver-staging.azurewebsites.net/evolis?printername=aprinter
Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/signalr/HubConnectionBuilder
        at Chat.main(Chat.java:16)
Caused by: java.lang.ClassNotFoundException: com.microsoft.signalr.HubConnectionBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

**Comment by shudson302** [comment] 2019-07-18 18:35
I tried this on a windows machine and on a linux on a raspberry PI

**Comment by shudson302** [comment] 2019-07-18 18:36
[java-client.zip](https://github.com/aspnet/SignalR-samples/files/3407957/java-client.zip)
